[project]
name = "aws-lambda-runner-phone-home"
version = "1.0.0"
description = "Simple lambda to inform Nuon that a cloudformation stack has been CRUD-ed"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "urllib3",
  "cfnresponse",
]
